### ISSUE TITLE
[Errno 98] Address already in use

### ISSUE THREAD

**Issue by MeredithZhou** [microsoft/JARVIS#118]
When I ran "python models_server.py --config config.gradio.yaml", got the error as follows

`[ ready ] 87.86034107208252s
Traceback (most recent call last):
  File "models_server.py", line 635, in <module>
    waitress.serve(app, host="0.0.0.0", port=port)
  File "/opt/bitnami/jupyterhub-singleuser/env/myenv_jarvis/lib/python3.8/site-packages/waitress/__init__.py", line 13, inserve
    server = _server(app, **kw)
  File "/opt/bitnami/jupyterhub-singleuser/env/myenv_jarvis/lib/python3.8/site-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/opt/bitnami/jupyterhub-singleuser/env/myenv_jarvis/lib/python3.8/site-packages/waitress/server.py", line 244, in __init__
    self.bind_server_socket()
  File "/opt/bitnami/jupyterhub-singleuser/env/myenv_jarvis/lib/python3.8/site-packages/waitress/server.py", line 361, in bind_server_socket
    self.bind(sockaddr)
  File "/opt/bitnami/jupyterhub-singleuser/env/myenv_jarvis/lib/python3.8/site-packages/waitress/wasyncore.py", line 396, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address already in use`

How can I fix it?

**Comment by tricktreat** [comment]
Maybe another program is using this port. You can use the `lsof` command to check the status of the port.
