### ISSUE TITLE
git lfs error

### ISSUE THREAD

**Issue by lawzlo** [microsoft/JARVIS#152]
Hey, I have the issue below. I ran git lfs install, and git lfs pull. But still got same error. 

My git lfs version: git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)

`(jarvis_env) PS F:\code\JARVIS\server> python models_server.py --config config.yaml
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "F:\code\JARVIS\jarvis_env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "F:\code\JARVIS\jarvis_env\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\code\JARVIS\jarvis_env\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\code\JARVIS\server\models_server.py", line 343, in <module>
    pipes = load_pipes(local_deployment)
  File "F:\code\JARVIS\server\models_server.py", line 88, in load_pipes
    "model": VisionEncoderDecoderModel.from_pretrained(f"{local_fold}/nlpconnect/vit-gpt2-image-captioning"),
  File "F:\code\JARVIS\jarvis_env\lib\site-packages\transformers\models\vision_encoder_decoder\modeling_vision_encoder_decoder.py", line 363, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "F:\code\JARVIS\jarvis_env\lib\site-packages\transformers\modeling_utils.py", line 2560, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "F:\code\JARVIS\jarvis_env\lib\site-packages\transformers\modeling_utils.py", line 447, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.`

**Comment by chenfengyanyu** [comment]
I had the same problem, even with git-lfs installed
