### ISSUE TITLE
Can run on windows platform?

### ISSUE THREAD

**Issue by WangShaoyu1** [microsoft/JARVIS#155]
after downlaod all models，excute the next command:
python models_server.py --config config.yaml  // local_deployment: standard

it goes wrong:
PS D:\gitlab\JARVIS\server> python models_server.py --config config.yaml
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Some weights of DPTForDepthEstimation were not initialized from the model checkpoint at models/Intel/dpt-large and are newly initialized: ['neck.fusion_stage.layers.0.residual_layer1.convolution2.bias', 'neck.fusion_stage.layers.0.residual_layer1.convolution1.weight', 'neck.fusion_stage.layers.0.residual_layer1.convolution2.weight', 'neck.fusion_stage.layers.0.residual_layer1.convolution1.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
[ ready ] 25.730659008026123s

**Comment by Slapbox** [comment]
The requirements say Ubuntu. It's pretty clear.

**Comment by Combustible-material** [comment]
> The requirements say Ubuntu. It's pretty clear.

It can run in windows11. tryed it . and successful 
all file = 295GB  ,terrible！

可以的，我在windows11中总署部并运行成功了。下载后占用295G硬盘空间。
运行后内存占用约28GB。 显卡占用却非常小，可能是因为我还没有让他执行重大任务吧。
我的配件配置如下：
CPU: i7 12700
内存: 32G
显卡: RTX 3060 12G

但是好像并不稳定，能和JARVIS聊几句，之后就崩溃了。
我想应该是我有什么东西没做对。继续摸索中。。。

下面是聊天过程及错误信息：

C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Welcome to Jarvis! A collaborative system that consists of an LLM as the controller and numerous expert models as collaborative executors. Jarvis can plan tasks, schedule Hugging Face models, generate friendly responses based on your requests, and help you with many things. Please enter your request (`exit` to exit).
[ User ]: hi
[ Jarvis ]:  Hello, is there something I can help you with?
[ User ]:


are you chatGPT3.5 or 4.0 ?
[ Jarvis ]:  I'm 3.5. Is there anything else I can help you with?
[ User ]: I chat with chatGPT 3.5 before,he can speak chinese. can you ?
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\u267b' in position 1031: illegal multibyte sequence
Call stack:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\JARVIS\server\awesome_chat.py", line 868, in run_task
    choose_str = choose_model(input, command, cand_models_info, api_key, api_type, api_endpoint)
  File "D:\JARVIS\server\awesome_chat.py", line 364, in choose_model
    logger.debug(messages)
Message: [{'role': 'system', 'content': '#2 Model Selection Stage: Given the user request and the parsed tasks, the AI assistant helps the user to select a suitable model from a list of models to process the user request. The assistant should focus more on the description of the model and find the model that has the most potential to solve requests and tasks. Also, prefer models with local inference endpoints for speed and stability.'}, {'role': 'user', 'content': 'I chat with chatGPT 3.5 before,he can speak chinese. can you ?'}, {'role': 'assistant', 'content': "{'task': 'text-to-speech', 'id': 1, 'dep': [0], 'args': {'text': 'I chat with chatGPT 3.5 before,he can speak chinese. can you ?'}}"}, {'role': 'user', 'content': 'Please choose the most suitable model from [{\'id\': \'espnet/kan-bayashi_ljspeech_vits\', \'inference endpoint\': [\'espnet/kan-bayashi_ljspeech_vits\'], \'likes\': 70, \'description\': \'\\n## ESPnet2 TTS pretrained model \\n### `kan-bayashi/ljspeech_vits`\\n♻️ Imported from https://zenodo.or\', \'tags\': [\'espnet\', \'audio\', \'text-to-speech\']}, {\'id\': \'mio/amadeus\', \'inference endpoint\': [\'mio/amadeus\', \'microsoft/speecht5_tts\', \'speechbrain/tts-tacotron2-ljspeech\', \'espnet/kan-bayashi_ljspeech_vits\'], \'likes\': 55, \'description\': \'\\n\\n## ESPnet2 TTS model \\n\\n### `mio/amadeus`\\n\\nThis model was trained by mio using [amadeus recipe](htt\', \'tags\': [\'espnet\', \'audio\', \'text-to-speech\']}, {\'id\': \'microsoft/speecht5_tts\', \'inference endpoint\': [\'mio/amadeus\', \'microsoft/speecht5_tts\', \'speechbrain/tts-tacotron2-ljspeech\', \'espnet/kan-bayashi_ljspeech_vits\'], \'likes\': 54, \'description\': \'\\n\\n# SpeechT5 (TTS task)\\n\\nSpeechT5 model fine-tuned for speech synthesis (text-to-speech) on LibriTTS\', \'tags\': [\'audio\', \'text-to-speech\']}, {\'id\': \'speechbrain/tts-tacotron2-ljspeech\', \'inference endpoint\': [\'mio/amadeus\', \'microsoft/speecht5_tts\', \'speechbrain/tts-tacotron2-ljspeech\', \'espnet/kan-bayashi_ljspeech_vits\'], \'likes\': 49, \'description\': \'\\n\\n<iframe src=\'https://ghbtns.com/github-btn.html?user=speechbrain&repo=speechbrain&type=star&count=\', \'tags\': [\'text-to-speech\', \'TTS\', \'speech-synthesis\', \'Tacotron2\', \'speechbrain\']}] for the task {\'task\': \'text-to-speech\', \'id\': 1, \'dep\': [0], \'args\': {\'text\': \'I chat with chatGPT 3.5 before,he can speak chinese. can you ?\'}}. The output must be in a strict JSON format: {"id": "id", "reason": "your detail reasons for the choice"}.'}]
Arguments: ()
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\JARVIS\server\awesome_chat.py", line 653, in model_inference
    inference_result = local_model_inference(model_id, data, task)
  File "D:\JARVIS\server\awesome_chat.py", line 628, in local_model_inference
    results = response.json()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ Jarvis ]:  Yes, I understand your request. Based on the inference results, I can confirm that I can speak Chinese. As for the workflow, I used ChatGPT for conversational tasks and ESPnet/kan-bayashi_ljspeech_vits for text-to-speech tasks. The inference results for the conversational task is 'Yes, I can speak Chinese. What would you like to discuss?', and the inference results for the text-to-speech task is an error message 'Expecting value: line 1 column 1 (char 0)'. The complete path or urls of files in inference results are not available. I hope this answers your question. Is there anything else I can help you with?
[ User ]:

**Comment by Combustible-material** [comment]
I ran it in windows11, but not stable, and something goes wrong.
i chat with JARVIS for rounds , then it crashed.
