### ISSUE TITLE
Starting server no module named 'diffusers' 

### ISSUE THREAD

**Issue by Sutek484** [microsoft/JARVIS#157]
A similar error on both 
(base) root@ubuntu:/JARVIS/server# python models_server.py --config config.yaml
Traceback (most recent call last):
  File "/JARVIS/server/models_server.py", line 7, in <module>
    from diffusers import DiffusionPipeline, StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
ModuleNotFoundError: No module named 'diffusers'

(base) root@ubuntu:/JARVIS/server# python awesome_chat.py --config config.yaml --mode cli
Traceback (most recent call last):
  File "/JARVIS/server/awesome_chat.py", line 17, in <module>
    from diffusers.utils import load_image
ModuleNotFoundError: No module named 'diffusers'

if anyone could help it would be awesome

**Comment by kenyhenry** [comment]
first :
`pip install diffusers`

then for the load_image here the code:

`def load_image(file_path):
    image = Image.open(file_path)
    return image`
