### ISSUE TITLE
unable to start in hugginface inference mode, help?

### ISSUE THREAD

**Issue by namastexlabs** [microsoft/JARVIS#167]
ive been trying to get jarvis to work, was able to install all dependencies, but it wont run with errors related to hugginface. i tried changing / reseting api keys, no luck.

heres the command output
![image_2023-04-18_041454823](https://user-images.githubusercontent.com/116504299/232700353-43f3e9cf-c137-4a48-99c1-54315cd2a732.png)

apreciate some help.

thanks
Felipe

**Comment by DahaeKimEsther** [comment]
Have you tried changing 'inference_mode' to huggingface from local or hybrid? It is in 'config.default.yaml' file.

**Comment by Aaryan369** [comment]
Not sure if this is what you are looking for, but, If you change the inference_mode parameter to huggingface, you wouldn't need to download any models into the local machine. The models will run using the HuggingFace API.

Change below in 'configs/config.default.yaml':
`inference_mode: huggingface`

**Comment by namastexlabs** [comment]
I already had done this, and it wouldn't start..  thanks anyways.

I'm trying to download the models and see what happens (been a week lol)

Thanks

Em qua., 26 de abr. de 2023 05:34, Aaryan YVS ***@***.***>
escreveu:

**Comment by namastexlabs** [comment]
still doesnt run, tried full and standard mode (been downloading the models for days now, lol), this is the most far I've gotten:

$ python models_server.py --config configs/config.yaml
Some weights of DPTForDepthEstimation were not initialized from the model checkpoint at models/Intel/dpt-large and are newly initialized: ['neck.fusion_stage.layers.0.residual_layer1.convolution2.bias', 'neck.fusion_stage.layers.0.residual_layer1.convolution2.weight', 'neck.fusion_stage.layers.0.residual_layer1.convolution1.bias', 'neck.fusion_stage.layers.0.residual_layer1.convolution1.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth" to /home/[USERNAME]/.cache/torch/hub/checkpoints/resnet50_a1_0-14fe96d1.pth
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet101_a1h-36d3f2aa.pth" to /home/[USERNAME]/.cache/torch/hub/checkpoints/resnet101_a1h-36d3f2aa.pth
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
text_config_dict is provided which will be used to initialize CLIPTextConfig. The value text_config["id2label"] will be overriden.
Traceback (most recent call last):
File "/home/[USERNAME]/ai-apps/JARVIS/server/models_server.py", line 343, in <module>
pipes = load_pipes(local_deployment)
File "/home/[USERNAME]/ai-apps/JARVIS/server/models_server.py", line 335, in load_pipes
"control": ControlNetModel.from_pretrained(f"{local_fold}/lllyasviel/sd-controlnet-seg", torch_dtype=torch.float16),
File "/home/[USERNAME]/miniconda3/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 534, in from_pretrained
model_file = _get_model_file(
File "/home/[USERNAME]/miniconda3/lib/python3.10/site-packages/diffusers/utils/hub_utils.py", line 272, in _get_model_file
raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory models/lllyasviel/sd-controlnet-seg
