### ISSUE TITLE
Run command "npm run dev“, get npm Error.

### ISSUE THREAD

**Issue by 1294549175** [microsoft/JARVIS#207]
After i try to start web service by "sudo npm run dev", i get some vue error.I paste Error Info behind.

pkuccadm@node1:/data/huwenp/cxj/JARVIS/web$ sudo npm run dev

> vue3-ts-vite-router-tailwindcss@0.0.0 dev /data/huwenp/cxj/JARVIS/web
> vite

/data/huwenp/cxj/JARVIS/web/node_modules/vite/bin/vite.js:2
import { performance } from 'node:perf_hooks'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue3-ts-vite-router-tailwindcss@0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue3-ts-vite-router-tailwindcss@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-06-07T08_41_05_074Z-debug.log

![捕获](https://github.com/microsoft/JARVIS/assets/30077829/90b6a551-06e8-44b3-96a7-bb88a6e8c639)

**Comment by Zack4DEV** [comment]
you need to update "NodeJs" : curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&sudo apt-get install -y nodejs

**Comment by HassanAliRizvi** [comment]
I updated NodeJS and ran **npm run dev**. It didn't work even after that but running **npm run dev** after running the command **nvm use node** works. **nvm use node** just makes sure you are using the latest node version
