### ISSUE TITLE
Error while starting models_server.py

### ISSUE THREAD

**Issue by loseryoda** [microsoft/JARVIS#28]
Hi,
attempting to install this on windows, had a few issues with installing pytorch at the start but after that i got this:

```
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\modeling_utils.py", line 98, in load_state_dict
    return safetensors.torch.load_file(checkpoint_file, device="cpu")
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\safetensors\torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[640, 2560]' is invalid for input of size 798399

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\modeling_utils.py", line 102, in load_state_dict
    if f.read().startswith("version"):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 40678: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\JARVIS\server\models_server.py", line 338, in <module>
    pipes = load_pipes(local_deployment)
  File "D:\AI\JARVIS\server\models_server.py", line 315, in load_pipes
    "control": ControlNetModel.from_pretrained(f"{local_fold}/lllyasviel/sd-controlnet-mlsd", torch_dtype=torch.float16),
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\modeling_utils.py", line 557, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\modeling_utils.py", line 114, in load_state_dict
    raise OSError(
OSError: Unable to load weights from checkpoint file for 'models/lllyasviel/sd-controlnet-mlsd\diffusion_pytorch_model.safetensors' at 'models/lllyasviel/sd-controlnet-mlsd\diffusion_pytorch_model.safetensors'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

any ideas?

**Comment by ErikDombi** [comment]
Minimum requirements says that Ubuntu 16.04 LTS is required

**Comment by gillmohnish** [comment]
If you are trying to load a PyTorch model from a TensorFlow checkpoint, set the 'from_tf' argument to 'True' while loading the model.

**Comment by 1hachem** [comment]
I think that the problem is with the path, in unix we use the forward slash `/` while in windows it's `\`, the path you causing the error contains both !
try to use wsl this could solve your issue.
