### ISSUE TITLE
KeyError: 'choices'

### ISSUE THREAD

**Issue by MatthewCaponi** [microsoft/JARVIS#33]
I am getting this error when using the cli:

Traceback (most recent call last):
  File "awesome_chat.py", line 970, in <module>
    cli()
  File "awesome_chat.py", line 941, in cli
    answer = chat_huggingface(messages)
  File "awesome_chat.py", line 850, in chat_huggingface 
    task_str = parse_task(context, input).strip()       
  File "awesome_chat.py", line 297, in parse_task       
    return send_request(data)
  File "awesome_chat.py", line 167, in send_request     
    return response.json()["choices"][0]["text"].strip()
KeyError: 'choices'
(jarvis) 

My prompt was this:
[ User ]: based on this image, assets\example_image.JPG , please tell me what you see.

**Comment by austinmw** [comment]
@MatthewCaponi  How did you fix this?
