### ISSUE TITLE
error for help

### ISSUE THREAD

**Issue by samqin123** [microsoft/JARVIS#38]
python models_server.py --config config.yaml

Traceback (most recent call last):
  File "models_server.py", line 23, in <module>
    import torchaudio
  File "/Users/qinxiaoqiang/miniconda3/envs/jarvis/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/Users/qinxiaoqiang/miniconda3/envs/jarvis/lib/python3.8/site-packages/torchaudio/_extension/__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op

**ImportError: cannot import name 'fail_with_message' from 'torchaudio._internal.module_utils'**

**Comment by StillKeepTry** [comment]
@samqin123  It seems this problem is caused by your installed torchaudio. One possible reason may be this [https://discuss.pytorch.org/t/cuda-11-6-deprecation-help/176218](https://discuss.pytorch.org/t/cuda-11-6-deprecation-help/176218).
