### ISSUE TITLE
Error when start web server.

### ISSUE THREAD

**Issue by lychees** [microsoft/JARVIS#48]
```
(jarvis) m200@DESKTOP-K0LFJU8:~/workdir/JARVIS/web$ npm run dev

> vue3-ts-vite-router-tailwindcss@0.0.0 dev
> vite

file:///home/m200/workdir/JARVIS/web/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

Any idea?

**Comment by yanancai** [comment]
@lychees , I also encountered the same error, how did you resolve this? Can you please share?

**Comment by yanancai** [comment]
Updates: Upgraded my nodejs to latest version, and it worked.
