### ISSUE TITLE
KeyError choices in gradio demo

### ISSUE THREAD

**Issue by austinmw** [microsoft/JARVIS#50]
```
2023-04-05 20:33:46,053 - awesome_chat - INFO - input:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/jarvis/lib/python3.8/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ec2-user/anaconda3/envs/jarvis/lib/python3.8/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/home/ec2-user/anaconda3/envs/jarvis/lib/python3.8/site-packages/gradio/blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ec2-user/anaconda3/envs/jarvis/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ec2-user/anaconda3/envs/jarvis/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ec2-user/anaconda3/envs/jarvis/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "run_gradio_demo.py", line 81, in bot
    message = chat_huggingface(all_messages, OPENAI_KEY)
  File "/home/ec2-user/SageMaker/JARVIS/server/awesome_chat.py", line 852, in chat_huggingface
    task_str = parse_task(context, input, openaikey).strip()
  File "/home/ec2-user/SageMaker/JARVIS/server/awesome_chat.py", line 306, in parse_task
    return send_request(data)
  File "/home/ec2-user/SageMaker/JARVIS/server/awesome_chat.py", line 173, in send_request
    return response.json()["choices"][0]["text"].strip()
KeyError: 'choices'
```

**Comment by ErikDombi** [comment]
Is your OpenAI API key set up correctly?

**Comment by austinmw** [comment]
I think so.. I just copied/pasted it in and hit enter

**Comment by tricktreat** [comment]
Have you tried CLI mode, does it work?

**Comment by austinmw** [comment]
@tricktreat Hi, I pulled the latest commit, but this error still remains for me.

**Comment by tricktreat** [comment]
@austinmw The startup steps are

```bash
python models_server.py --config config.gradio.yaml
python run_gradio_demo.py --config config.gradio.yaml
```

Let me know if you followed this step to start Gradio?

**Comment by austinmw** [comment]
@tricktreat

- pulled latest commit
- ran above steps you provided

Still get the error.

**Comment by tricktreat** [comment]
@austinmw I'm having a hard time reproducing your issue. Please take a look at server/logs/debug.log .

**Comment by austinmw** [comment]
Ahh, very sorry, it looks like I reached account quota without realizing, apologies!!
