### ISSUE TITLE
Could not load model models/ydshieh/vit-gpt2-coco-en

### ISSUE THREAD

**Issue by e-oldman** [microsoft/JARVIS#54]
1. All installation steps has been completed
2. Running `python models_server.py --config config.yaml`
3. Getting this output with error
```
Fetching 27 files: 100%|██████████████████████████████████████████████████████████████████████████████| 27/27 [00:00<00:00, 338048.38it/s]
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
WARNING:datasets.builder:Found cached dataset cmu-arctic-xvectors (/home/user/.cache/huggingface/datasets/cmu-arctic-xvectors/default/0.0.1/a62fea1f9415e240301ea0042ffad2a3aadf4d1caa7f9a8d9512d631723e781f)
WARNING:datasets.builder:Found cached dataset cmu-arctic-xvectors (/home/user/.cache/huggingface/datasets/cmu-arctic-xvectors/default/0.0.1/a62fea1f9415e240301ea0042ffad2a3aadf4d1caa7f9a8d9512d631723e781f)
Some weights of DPTForDepthEstimation were not initialized from the model checkpoint at models/Intel/dpt-large and are newly initialized: ['neck.fusion_stage.layers.0.residual_layer1.convolution1.weight', 'neck.fusion_stage.layers.0.residual_layer1.convolution2.bias', 'neck.fusion_stage.layers.0.residual_layer1.convolution2.weight', 'neck.fusion_stage.layers.0.residual_layer1.convolution1.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Traceback (most recent call last):
  File "models_server.py", line 342, in <module>
    pipes = load_pipes(local_deployment)
  File "models_server.py", line 261, in load_pipes
    "model": pipeline(task="image-to-text", model=f"{local_fold}/ydshieh/vit-gpt2-coco-en"), 
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 779, in pipeline
    framework, model = infer_framework_load_model(
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/site-packages/transformers/pipelines/base.py", line 271, in infer_framework_load_model
    raise ValueError(f"Could not load model {model} with any of the following classes: {class_tuple}.")
ValueError: Could not load model models/ydshieh/vit-gpt2-coco-en with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForVision2Seq'>, <class 'transformers.models.vision_encoder_decoder.modeling_vision_encoder_decoder.VisionEncoderDecoderModel'>).
```

**Comment by ErikDombi** [comment]
You need to install `git lfs` and re-run the download script in `server/models/`

**Comment by e-oldman** [comment]
I did, all models are present, here's the `./download.sh` output:
```
----- Downloading from https://huggingface.co/nlpconnect/vit-gpt2-image-captioning -----
Already up to date.
----- Downloading from https://huggingface.co/lllyasviel/ControlNet -----
Already up to date.
----- Downloading from https://huggingface.co/lllyasviel/sd-controlnet-canny -----
Already up to date.
----- Downloading from https://huggingface.co/lllyasviel/sd-controlnet-depth -----
Already up to date.
----- Downloading from https://huggingface.co/lllyasviel/sd-controlnet-hed -----
Already up to date.
----- Downloading from https://huggingface.co/lllyasviel/sd-controlnet-mlsd -----
Already up to date.
----- Downloading from https://huggingface.co/lllyasviel/sd-controlnet-openpose -----
Already up to date.
----- Downloading from https://huggingface.co/lllyasviel/sd-controlnet-scribble -----
Already up to date.
----- Downloading from https://huggingface.co/lllyasviel/sd-controlnet-seg -----
Already up to date.
----- Downloading from https://huggingface.co/runwayml/stable-diffusion-v1-5 -----
Already up to date.
----- Downloading from https://huggingface.co/Salesforce/blip-image-captioning-large -----
Already up to date.
----- Downloading from https://huggingface.co/damo-vilab/text-to-video-ms-1.7b -----
Already up to date.
----- Downloading from https://huggingface.co/microsoft/speecht5_asr -----
Already up to date.
----- Downloading from https://huggingface.co/facebook/maskformer-swin-large-ade -----
Already up to date.
----- Downloading from https://huggingface.co/microsoft/biogpt -----
Already up to date.
----- Downloading from https://huggingface.co/facebook/esm2_t12_35M_UR50D -----
Already up to date.
----- Downloading from https://huggingface.co/JorisCos/DCCRNet_Libri1Mix_enhsingle_16k -----
Already up to date.
----- Downloading from https://huggingface.co/espnet/kan-bayashi_ljspeech_vits -----
Already up to date.
----- Downloading from https://huggingface.co/facebook/detr-resnet-101 -----
Already up to date.
----- Downloading from https://huggingface.co/microsoft/speecht5_tts -----
Already up to date.
----- Downloading from https://huggingface.co/microsoft/speecht5_hifigan -----
Already up to date.
----- Downloading from https://huggingface.co/microsoft/speecht5_vc -----
Already up to date.
----- Downloading from https://huggingface.co/openai/whisper-base -----
Already up to date.
----- Downloading from https://huggingface.co/Intel/dpt-large -----
Already up to date.
----- Downloading from https://huggingface.co/facebook/detr-resnet-50-panoptic -----
Already up to date.
----- Downloading from https://huggingface.co/facebook/detr-resnet-50 -----
Already up to date.
----- Downloading from https://huggingface.co/google/owlvit-base-patch32 -----
Already up to date.
----- Downloading from https://huggingface.co/impira/layoutlm-document-qa -----
Already up to date.
----- Downloading from https://huggingface.co/ydshieh/vit-gpt2-coco-en -----
Already up to date.
----- Downloading from https://huggingface.co/dandelin/vilt-b32-finetuned-vqa -----
Already up to date.
----- Downloading from https://huggingface.co/lambdalabs/sd-image-variations-diffusers -----
Already up to date.
----- Downloading from https://huggingface.co/facebook/maskformer-swin-base-coco -----
Already up to date.
----- Downloading from https://huggingface.co/Intel/dpt-hybrid-midas -----
Already up to date.
----- Downloading from https://huggingface.co/datasets/Matthijs/cmu-arctic-xvectors -----
Already up to date.
```

**Comment by tricktreat** [comment]
Can you check your transformer version? We recommend installing the version specified in `requirements.txt`.

**Comment by ErikDombi** [comment]
How large is your Models folder? Mine was around 275 GB.

**Comment by e-oldman** [comment]
> Can you check your transformers version? We recommend installing the version specified in `requirements.txt`.

import transformers
print(transformers.__version__)
# 4.28.0.dev0

**Comment by e-oldman** [comment]
Seems like it's been resolved by deleting `ydshieh/vit-gpt2-coco-en` and running `./download.sh` again
