### ISSUE TITLE
Gradio. Built-in example - Joke and Cat. json.decoder.JSONDecodeError: Invalid \escape

### ISSUE THREAD

**Issue by e-oldman** [microsoft/JARVIS#60]
Server is up an running. Using gradio `python run_gradio_demo.py --config config.gradio.yaml`:
```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

Running built-in example `show me a joke and an image of cat`. Gradio terminal output:
```
2023-04-06 15:45:43,407 - awesome_chat - INFO - ********************************************************************************
2023-04-06 15:45:43,407 - awesome_chat - INFO - input: show me a joke and an image of cat
2023-04-06 15:45:45,739 - awesome_chat - INFO - [{"task": "conversational", "id": 0, "dep": [-1], "args": {"text": "please show me a joke of cat" }}, {"task": "text-to-image", "id": 1, "dep": [-1], "args": {"text": "a photo of cat" }}]
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/site-packages/gradio/blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "run_gradio_demo.py", line 81, in bot
    message = chat_huggingface(all_messages, OPENAI_KEY)
  File "/home/user/Developer/JARVIS/server/awesome_chat.py", line 908, in chat_huggingface
    response = response_results(input, results, openaikey).strip()
  File "/home/user/Developer/JARVIS/server/awesome_chat.py", line 342, in response_results
    messages = json.loads(demos_or_presteps)
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user/anaconda3/envs/jarvis/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 8 column 398 (char 527)

```

**Comment by tricktreat** [comment]
Let me know if the latest commit resolves the issue.

**Comment by e-oldman** [comment]
It did, thank you!
